# Generated by Django 3.1.6 on 2021-06-06 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='details',
            old_name='password1',
            new_name='password',
        ),
        migrations.RemoveField(
            model_name='details',
            name='password2',
        ),
    ]
