# Generated by Django 3.1.6 on 2021-06-06 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0002_auto_20210606_1144'),
    ]

    operations = [
        migrations.AddField(
            model_name='details',
            name='number',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
