# Generated by Django 3.1.6 on 2021-07-04 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0005_images'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Images',
        ),
    ]
