# Generated by Django 3.1.6 on 2021-07-05 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0006_delete_images'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Details',
            new_name='User_data',
        ),
    ]
